blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/thriving-dev/kafka-streams-cassandra-state-store/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
